import { Home } from "@mui/icons-material";

const properties = [
  { label: "Residential Properties", header: true },
  { label: "Single-Family Home", header: false, icon: <Home /> },
  { label: "Apartments/Condominium", header: false, icon: <Home /> },
  { label: "Townhouse", header: false, icon: <Home /> },
  { label: "Duplex/Triplex", header: false, icon: <Home /> },
  { label: "Co-ops (Cooperative Apartment)", header: false, icon: <Home /> },
  { label: "Mobile Home", header: false, icon: <Home /> },
  { label: "Commercial Propertie", header: true },
  { label: "Office Building", header: false },
  { label: "Retail Space", header: false },
  { label: "Industrial/Warehouse Building", header: false },
  { label: "Mixed-Use Building", header: false },
  { label: "Hotel/Motel", header: false },
  { label: "Restaurant", header: false },
  { label: "Industrial Property", header: true },
  { label: "Manufacturing Facility", header: false },
  { label: "Warehouse", header: false },
  { label: "Distribution Center", header: false },
  { label: "Factory", header: false },
  { label: "Retail Property", header: true },
  { label: "Shopping Centers/Mall", header: false },
  { label: "Standalone Retail Store", header: false },
  { label: "Strip Mall", header: false },
  { label: "Hospitality Property", header: true },
  { label: "Hotel", header: false },
  { label: "Resort", header: false },
  { label: "Bed and Breakfast", header: false },
  { label: "Special Purpose Property", header: true },
  { label: "Hospitals/Healthcare Facility", header: false },
  { label: "Educational Institutions/School", header: false },
  { label: "Religious Building", header: false },
  { label: "Sports Facility", header: false },
  { label: "Vacant Land", header: true },
  { label: "Undeveloped Land", header: false },
  { label: "Agricultural Land", header: false },
  { label: "Residential Land", header: false },
  { label: "Recreational Property", header: true },
  { label: "Vacation Homes", header: false },
  { label: "Cabins/Cottages", header: false },
  { label: "Lakefront Property", header: false },
  { label: "Investment Property", header: true },
  { label: "Rental Property", header: false },
  { label: "Real Estate Investment Trusts (REITs)", header: false },
  { label: "Government Property", header: true },
  { label: "Government Building", header: false },
  { label: "Military Base", header: false },
  { label: "Historical Property", header: true },
  { label: "Historic Home", header: false },
  {
    label: "Buildings with Cultural or Historical Significance",
    header: false,
  },
];

export default properties;
